//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odb
    {
        public int VOppID { get; set; }
        public string OName { get; set; }
        public System.DateTime ODate { get; set; }
        public string OCenter { get; set; }
        public string OSkills { get; set; }
    }
}
