//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VMSystem
    {
        [Key]
        public int VMID { get; set; }

        [Display(Name="First Name")]
        public string VFirstName { get; set; }
        [Display(Name = "Last Name")]
        public string VLastName { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string VEmail { get; set; }
        [Display(Name = "Username")]
        public string VUsername { get; set; }
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string VPassword { get; set; }
        [Display(Name = "Phone")]
        public string VMobile { get; set; }
    }
}
