//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPStatu
    {
        public int VPID { get; set; }
        public string VPFName { get; set; }
        public string VPLName { get; set; }
        public string VPUsername { get; set; }
        public string VPPassword { get; set; }
        public string VPCenter { get; set; }
        public string VPSkills { get; set; }
        public System.DateTime VPAvailability { get; set; }
        public string PAddress { get; set; }
        public string VPhone { get; set; }
        public string VPEmail { get; set; }
        public string VPStatus { get; set; }
    }
}
